### ISSUE TITLE
Switch Unicode emoji to emoji codes

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/Aerophyl#12]
Currently:
```json
{
  ":cactus": "",
}
```

Should be:
```json
{
  ":cactus": "cactus",
  ":spaceship": "rocket",
  ":mappa": ".sarcasm"
}
```

Note the use of the `.` prefix for custom emojis. (For example, although `:sarcasm:` isn't an emoji, we can convert between `:mappa` and `Kappa` by using `.sarcasm` for both.)

**Comment by Innectic** [comment]
Done in #30
