### ISSUE TITLE
Bot ignores rate limits

### ISSUE THREAD

**Issue by 2Cubed** [CactusDev/Aerophyl#9]
@2Cubed commented on [Sat May 27 2017](https://github.com/CactusDev/CactusBot/issues/308)

The bot ignores rate limits, trying to send messages whenever they are received. This especially impacts responses that are split over multiple chat messages.

---

@Innectic commented on [Sat May 27 2017](https://github.com/CactusDev/CactusBot/issues/308#issuecomment-304430497)

Important thing: Each service handler needs to implement this some how. Different services have different rate limits.

---

@2Cubed commented on [Mon May 29 2017](https://github.com/CactusDev/CactusBot/issues/308#issuecomment-304726138)

We should probably have a generalized ratelimit method somewhere in the `WebSocket` class, which can either be used or ignored by the individual services.

---

@Innectic commented on [Mon May 29 2017](https://github.com/CactusDev/CactusBot/issues/308#issuecomment-304750154)

It shouldn't be able to be ignored. It should be required.

---

@Alkali-Metal commented on [Thu Jun 08 2017](https://github.com/CactusDev/CactusBot/issues/308#issuecomment-307235537)

Maybe make it so that if a service rate limit isn't supplied by the handler (Or whatever would handle it) it then falls back to the default one and can't be bypassed?

**Comment by Innectic** [comment]
No longer relevant
